[package]
name = "spooky"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.34"
tokio = { version = "1", features = ["full"] }

quinn = "0.11.9"
rustls = { version = "0.23.31", features = ["ring"] }
rustls-pki-types = "1.12.0"

h3 = "0.0.8"
h3-quinn = "0.0.10"
http = "1.3.1"

bytes = "1.10.1"
