[package]
name = "impulse"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "impulse"
path = "src/main.rs"

[dependencies]
clap.workspace = true
log.workspace = true
tokio.workspace = true
quiche.workspace = true
rand.workspace = true
bytes.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
libc.workspace = true
core_affinity.workspace = true

impulse-config = { path = "../crates/config" }
impulse-edge = { path = "../crates/edge" }
impulse-utils = { path = "../crates/utils" }
