[package]
name = "impulse-bridge"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
http.workspace = true
quiche.workspace = true
bytes.workspace = true
http-body-util.workspace = true
hyper.workspace = true
itoa.workspace = true
smallvec.workspace = true
impulse-errors = { path = "../errors" }
impulse-config = { path = "../config" }

[[test]]
name = "regression"
path = "tests/regression/main.rs"
